name: KABA
description: Kaba under Flutter framework

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.2.9

environment:
  sdk: ">=2.2.0 <3.0.0"

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
#  intl_translation: any
#  flutter_launcher_icons: "^0.8.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # Add this line
  flutter_redux: ^0.8.2
  location: ^4.3.0
  flutter_redux_dev_tools: ^0.5.1
  shared_preferences: ^2.0.5
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.0
  carousel_slider: ^4.0.0
  #  webview_flutter: ^0.3.21
  flutter_inner_drawer: ^1.0.0+1
  rxdart: ^0.27.0
  toast: ^0.1.5
  google_maps_flutter: ^2.1.1
  geolocator: ^8.0.1
  permission_handler: ^8.3.0
  place_picker: ^0.9.18
  font_awesome_flutter: ^9.0.0
  #  flutter_qr_reader: ^1.0.2
  qr_flutter: ^4.0.0
  image_picker: ^0.8.4+4
  flutter_datetime_picker: ^1.5.1
  firebase_analytics: ^9.0.4
  photo_view: ^0.13.0
  vibration: ^1.2.4
  country_code_picker: ^2.0.1
  device_info: ^2.0.0
  audioplayer: 0.8.1
  audioplayer_web: 0.7.1
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.1.0
  url_launcher: ^6.0.6
  flare_flutter: ^3.0.0
  tinycolor: ^1.0.2
  provider: ^6.0.1
  shimmer_animation: ^2.0.0
  awesome_loader: ^0.0.3
  bouncing_widget:
    git:
      url: "https://github.com/blackgerman/bouncing_widget.git"
  uni_links: ^0.5.1
  qr_code_scanner: ^0.6.1
  #  twitter_qr_scanner: any
  share: ^2.0.1
  #  pub_semver: ^1.4.4
#  android_intent_plus: ^3.0.2
  intro_views_flutter: '^3.2.0'
  #  flutter_statusbar_manager: ^1.0.2
  #  flutter_inappwebview: ^2.1.0+1
  package_info: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  pinch_zoom: ^1.0.0
  flutter_linkify: ^5.0.2
  flutter_icons: ^1.1.0
  iphone_has_notch: ^1.0.0
  clipboard: ^0.1.3
  whatsapp_unilink: ^2.0.0
  http: ^0.13.3
  dio: ^4.0.4
  overlay_support: ^1.2.1
  flutter_switch: ^0.3.2
#  sentry_flutter: ^6.5.0
#  huawei_push: ^5.3.0+304



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
    - family: Dosis-Light
      fonts:
        - asset: assets/fonts/Dosis-Light.ttf
          weight: 200
    - family: Dosis-Bold
      fonts:
        - asset: assets/fonts/Dosis-Bold.ttf
          weight: 600
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # localization
    - assets/i18n/fr.json
    - assets/i18n/en.json
    - assets/i18n/zh.json
    # images
    - assets/flare/newmessage.flr
    - assets/flare/success_check.flr
    - assets/images/vectors/closedshop.svg
    - assets/images/vectors/ic_kaba_main_logo.svg
    - assets/images/vectors/ic_voucher.svg
    - assets/images/vectors/fl_deliveryman.svg
    - assets/images/vectors/fl_question.svg
    - assets/images/vectors/address_creation_ok.svg
    - assets/images/vectors/address_creation_error.svg
    - assets/fonts/MyFlutterApp.ttf
    - assets/images/png/kaba_ico.png
    - assets/images/png/whatsapp.png
    - assets/images/png/kaba_logo_red_man.png
    - assets/images/png/kaba_logo_red_man.png
    - assets/images/png/kaba_copyright_presentation.png
    - assets/images/png/ic_transaction_success.png
    - assets/images/png/arrived.png
    - assets/images/png/login_description.png
    - assets/images/png/payment.png
    - assets/images/png/address.png
    - assets/images/png/choice.png
    - assets/images/png/enjoy.png
    - assets/images/png/diaspora.png
    - assets/images/png/smartphone_unlock.png
    - assets/images/png/location_check_ok.png
    - assets/images/png/alarm.png
    - assets/images/png/demo.png
    # presentation
    - assets/images/vectors/app_presentation/sl_enjoy.svg
    - assets/images/vectors/app_presentation/sl_choice.svg
    - assets/images/vectors/app_presentation/sl_geolocalisation.svg
    - assets/images/vectors/app_presentation/sl_payment.svg
    - assets/images/vectors/transfer_money.svg
    - assets/images/vectors/balance.svg
    # icons
    - assets/images/vectors/prepaid.svg
    - assets/images/vectors/agreement.svg
    - assets/images/vectors/out_of_range.svg
    - assets/images/vectors/notificiation_message_normal.svg
    - assets/images/vectors/notification_message_new.svg
    - assets/images/vectors/account_balance.svg
    - assets/images/vectors/coupon.svg
    - assets/command_success_hold_on.mp3
    - assets/money_transfer_successfull.mp3
    - assets/new_message.mp3
    - assets/scan_catch.mp3
    - assets/voucher_subscribe_success.mp3
  # test splash screen
    - assets/images/jpg/flu_splash.jpeg
  #  - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
