enum ExpeditionStatus {
  DEMANDE_FAITE("DEMANDE_FAITE"),
  NEGOCIATION("NEGOCIATION"),
  PAIEMENT("PAIEMENT"),
  RECUPERATION_EFFECTUEE("RECUPERATION_EFFECTUEE"),
  DEPART_CONFIRME("DEPART_CONFIRME"),
  EN_COURS_EXPEDITION("EN_COURS_EXPEDITION"),
  ARRIVE_EN_VILLE("ARRIVE_EN_VILLE"),
  LIVRAISON_AU_DESTINATAIRE("LIVRAISON_AU_DESTINATAIRE");
  final String value;
  const ExpeditionStatus(this.value);
}