enum ExpeditionStatus {
  EN_ATTENTE("EN_ATTENTE"),
  NEGOCIATION("NEGOCIATION"),
  REJETEE("REJETEE"),
  ACCEPTEE("ACCEPTEE"),
  RECUPERATION_EFFECTUEE("RECUPERATION_EFFECTUEE"),
  DEPART_CONFIRME("DEPART_CONFIRME"),
  EN_COURS_EXPEDITION("EN_COURS_EXPEDITION"),
  ARRIVE_EN_VILLE("ARRIVE_EN_VILLE"),
  LIVRAISON_AU_DESTINATAIRE("LIVRAISON_AU_DESTINATAIRE"),
  PAIEMENT("PAIEMENT");
  final String value;
  const ExpeditionStatus(this.value);

  @override
  String toString() => value;
}
